package pt.isec.agileMath.constants

enum class GameState {
    START_NEW_GAME,
    NEW_LEVEL_COUNTDOWN_TICK,
    LEVEL_COMPLETED,
    NEW_LEVEL_STARTED,
    GAME_OVER_TIME_OUT,
    CLOCK_TICK,
    CORRECT_EXPRESSION,
    FAILED_EXPRESSION
}