package pt.isec.agileMath.constants


enum class GameState {
    GAME_STARTED,
    NEW_LEVEL_COUNTDOWN_TICK,
    NEW_LEVEL_COUNTDOWN_PAUSED,
    NEW_LEVEL_COUNTDOWN_RESUMED,
    LEVEL_COMPLETED,
    NEW_LEVEL_STARTED,
    GAME_OVER_TIME_OUT,
    GAME_OVER,
    CLOCK_TICK,
    VALIDATE_EXPRESSION,
    CORRECT_EXPRESSION,
    FAILED_EXPRESSION,

    // Multiplayer
    START_AS_HOST,
    START_AS_CLIENT,
    CONNECT_CLIENT,
    CLIENT_CONNECTED,
    CLIENT_DISCONNECTED,
    WAITING_GAME_CONFIGS,

    CONNECTION_ENDED,
    CONNECTION_ERROR,
    CONNECTION_ESTABLISHED,
    CONNECTION_TO_SERVER_ERROR,
    CONNECTION_TO_SERVER_ESTABLISHED,

    SOCKET_ERROR,

    // Multiplayer UI
    REFRESH_PLAYERS_LIST,
    REFRESH_UI,

    NONE
}