package pt.isec.agileMath.constants

enum class GameState {
    START_NEW_GAME,
    NEW_LEVEL_COUNTDOWN_TICK,
    NEW_LEVEL_COUNTDOWN_PAUSED,
    NEW_LEVEL_COUNTDOWN_RESUMED,
    LEVEL_COMPLETED,
    NEW_LEVEL_STARTED,
    GAME_OVER_TIME_OUT,
    GAME_OVER,
    CLOCK_TICK,
    CORRECT_EXPRESSION,
    FAILED_EXPRESSION,

    // Multiplayer
    START_AS_HOST,
    START_AS_CLIENT,
    CLIENT_CONNECTED,
    SETTING_PARAMETERS,
    CLIENT_DISCONNECTED,
    WAITING_GAME_CONFIGS,

    CONNECTION_ENDED,
    CONNECTION_ERROR,
    CONNECTION_ESTABLISHED,
    CONNECTION_TO_SERVER_ERROR,

    // Multiplayer UI
    REFRESH_PLAYERS_LIST,
    REFRESH_UI
}